name: Build Assimp Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -G Ninja
          -DBUILD_SHARED_LIBS=ON
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      #
      # Complete build output
      #
      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: assimp-build-release
          compression-level: 0
          path: |
            build/bin/Release/**
            build/lib/Release/**
            build/code/Release/**
            build/*.sln
            build/**/*.vcxproj
            build/**/*.pdb
            build/**/*.dll
            build/**/*.lib
            build/**/*.exe

      #
      # 

      #
      # Optional: source snapshot
      #
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: assimp-source
          path: |
            include/**
            code/**
            CMakeLists.txt
            LICENSE
            Readme.md
